# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Podfile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Podfile

end

target 'Pods' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Pods

  target 'PodsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PodsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'WeatherWithViper' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WeatherWithViper

  target 'WeatherWithViperTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WeatherWithViperUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
